In [2]:
import numpy as np

In [5]:
test_array = np.array(["1", "4", 5, 8], np.float32)
test_array

array([1., 4., 5., 8.], dtype=float32)

In [6]:
type(test_array[3])

numpy.float32

In [7]:
test_array.dtype

dtype('float32')

In [8]:
test_array.shape # tuple형태로 출력

(4,)

In [9]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape # tuple형태로 출력(3행4열)

(3, 4)

In [10]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape # (4,3,4 : 깊이, 행, 열)

(4, 3, 4)

In [11]:
np.array(tensor, int).ndim # ndim : 크기

3

In [12]:
np.array(tensor, int).size # data의 갯수

48

In [14]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float32).nbytes 
# 24 : 32bits = 4bytes -> 6 * 4bytes

24

In [15]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.int8).nbytes
# 6 : 8bits = 1bytes -> 6 * 1bytes

6

In [16]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float64).nbytes
# 48 : 64bits = 8bytes -> 6 * 8bytes

48

In [17]:
# reshape : array의 shape의 크기를 변경
# array의 size만 같다면 다차원으로 자유로이 변형가능
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [18]:
np.array(test_matrix).reshape(8, )

array([1, 2, 3, 4, 1, 2, 5, 8])

In [19]:
np.array(test_matrix).reshape(8, ).shape

(8,)

In [20]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [21]:
np.array(test_matrix).reshape(-1,2).shape # -1 : size를 기반으로 row개수를 지정

(4, 2)

In [22]:
# flatten : 다차원 array를 1차원 array로 변환
test_matrix = [[[1,2,3,4],[1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [23]:
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)
print(a[0,0])
print(a[0][0]) # a[0,0]과 동일

[[1 2 3]
 [4 5 6]]
1
1


In [24]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
a[:,2:] # 전체 row의 2열 이상
a[1,1:3] # 1행의 1열~2열
a[1:3] # 1행~2행 전체

array([[ 6,  7,  8,  9, 10]])

In [3]:
# arange : array의 범위를 지정하여, 값의 list를 생성
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
# ones, zeros, empty : 1, 0으로 가득한 ndaarray생성 empty : 메모리 공간만 잡아준다.
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.empty(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# something_like : 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [11]:
# indentity : 단위행렬을 생성
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [16]:
# eye : 대각선이 1인 행렬 생성
np.eye(N=3, M=5, dtype=np.int8) # n : 행 / m : 열

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [17]:
np.eye(3, 5, k=2) # k : 시작 인덱스

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# diag : 대각 행렬의 값을 추출
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [19]:
np.diag(matrix, k=1) # k : 시작 인덱스

array([1, 5])

In [20]:
# random sampling : 데이터 분포에 따른 sampling으로 array 생성
np.random.uniform(0,1,10).reshape(2,5) # 균등분포

array([[0.68793957, 0.22920606, 0.49789838, 0.2911985 , 0.74906004],
       [0.50528689, 0.07955862, 0.04762207, 0.02906425, 0.1125641 ]])

In [22]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포

array([[ 0.25160184, -0.3801772 , -0.8253532 ,  0.35374184,  0.35746483],
       [-0.05355477, -1.0607096 ,  1.39069934,  0.21308421, -0.45128807]])