In [1]:
import numpy as np

In [5]:
test_array = np.array(["1", "4", 5, 8], np.float32)
test_array

array([1., 4., 5., 8.], dtype=float32)

In [6]:
type(test_array[3])

numpy.float32

In [7]:
test_array.dtype

dtype('float32')

In [8]:
test_array.shape # tuple형태로 출력

(4,)

In [9]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape # tuple형태로 출력(3행4열)

(3, 4)

In [10]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape # (4,3,4 : 깊이, 행, 열)

(4, 3, 4)

In [11]:
np.array(tensor, int).ndim # ndim : 크기

3

In [12]:
np.array(tensor, int).size # data의 갯수

48

In [14]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float32).nbytes 
# 24 : 32bits = 4bytes -> 6 * 4bytes

24

In [15]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.int8).nbytes
# 6 : 8bits = 1bytes -> 6 * 1bytes

6

In [16]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float64).nbytes
# 48 : 64bits = 8bytes -> 6 * 8bytes

48

In [17]:
# reshape : array의 shape의 크기를 변경
# array의 size만 같다면 다차원으로 자유로이 변형가능
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [18]:
np.array(test_matrix).reshape(8, )

array([1, 2, 3, 4, 1, 2, 5, 8])

In [19]:
np.array(test_matrix).reshape(8, ).shape

(8,)

In [20]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [21]:
np.array(test_matrix).reshape(-1,2).shape # -1 : size를 기반으로 row개수를 지정

(4, 2)

In [22]:
# flatten : 다차원 array를 1차원 array로 변환
test_matrix = [[[1,2,3,4],[1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [23]:
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)
print(a[0,0])
print(a[0][0]) # a[0,0]과 동일

[[1 2 3]
 [4 5 6]]
1
1


In [24]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
a[:,2:] # 전체 row의 2열 이상
a[1,1:3] # 1행의 1열~2열
a[1:3] # 1행~2행 전체

array([[ 6,  7,  8,  9, 10]])

In [3]:
# arange : array의 범위를 지정하여, 값의 list를 생성
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
# ones, zeros, empty : 1, 0으로 가득한 ndaarray생성 empty : 메모리 공간만 잡아준다.
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.empty(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# something_like : 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [11]:
# indentity : 단위행렬을 생성
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [16]:
# eye : 대각선이 1인 행렬 생성
np.eye(N=3, M=5, dtype=np.int8) # n : 행 / m : 열

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [17]:
np.eye(3, 5, k=2) # k : 시작 인덱스

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# diag : 대각 행렬의 값을 추출
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [19]:
np.diag(matrix, k=1) # k : 시작 인덱스

array([1, 5])

In [20]:
# random sampling : 데이터 분포에 따른 sampling으로 array 생성
np.random.uniform(0,1,10).reshape(2,5) # 균등분포

array([[0.68793957, 0.22920606, 0.49789838, 0.2911985 , 0.74906004],
       [0.50528689, 0.07955862, 0.04762207, 0.02906425, 0.1125641 ]])

In [22]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포

array([[ 0.25160184, -0.3801772 , -0.8253532 ,  0.35374184,  0.35746483],
       [-0.05355477, -1.0607096 ,  1.39069934,  0.21308421, -0.45128807]])

In [3]:
# sum : ndarray의 element들 간의 합을 구함
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
test_array.sum(dtype=np.float)

55.0

In [5]:
# axis : 모든 operation function을 실행할 때, 기준이 되는 dimension축
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
test_array.sum(axis=1), test_array.sum(axis=0) # axis : 차원? 

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [2]:
# mean & std : ndarray의 element들 간의 평균 또는 표준 편차를 반환
test_array = np.arange(1, 13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
test_array.mean(), test_array.mean(axis=0) # mean : 평균

(6.5, array([5., 6., 7., 8.]))

In [4]:
test_array.std(), test_array.std(axis=0) # std : 표준편차

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [5]:
# concatenate : numpy array를 합치는 함수
# vstack : 행으로 합침
# hstack : 열로 합침
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [8]:
# concatenate : axis를 기준으로 합침
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
# element-wist operations : array간 shape이 같을 때 일어나는 연산
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a # shape이 같으면 같은 위치에 있는 것 끼리 곱함

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [13]:
# dot product : 일반적인 행렬 곱
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [14]:
# broadcasting : shape이 다른 배열 간 연산을 지원하는 기능
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
test_matrix + scalar # 모든 원소에 scalar값을 더해줌

array([[4., 5., 6.],
       [7., 8., 9.]])

In [15]:
# all & any : array의 데이터 전부 / 일부 가 조건에 만족 여부 반환
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.any(a>5), np.any(a<0)

(True, False)

In [17]:
np.all(a>5), np.all(a<10)

(False, True)

In [18]:
# logical_and : and조건이 모두 만족할때(논리 곱)
a = np.array([1,3,0],float)
np.logical_and(a>0,a<3)

array([ True, False, False])

In [19]:
# logical_not : false일때 참
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [20]:
# where : 조건에 만족하는 인덱스값을 반환
np.where(a>0, 3, 2) # a > 0의 조건이 만족할 경우, 3반환 / 아니면 2 반환

array([3, 3, 2])

In [21]:
np.where(a>0) 

(array([0, 1], dtype=int64),)

In [22]:
# argmax & argmin : 최대 / 최소 인덱스 값 반환
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [23]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0) # axis축을 기준으로 찾기

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

In [24]:
# boolean index
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [25]:
test_array[test_array > 3] # 조건에 만족되는 것만 반환

array([4., 8., 9., 7.])

In [26]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B.astype(np.int) # true, false를 1, 0으로 바꿔서 출력

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

In [27]:
# fancy index : numpy는 array를 index value로 사용해서 값을 추출하는 방법
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # index값 / 반드시 int형으로 선언
a[b] 

array([2., 2., 4., 8., 6., 4.])

In [28]:
# take : bracket index와 같은 효과
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [29]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c] # b와 c를 열로 묶어서 ex)0행 0열 추출

array([ 1.,  4., 16., 16.,  4.])