In [1]:
import numpy as np

In [5]:
test_array = np.array(["1", "4", 5, 8], np.float32)
test_array

array([1., 4., 5., 8.], dtype=float32)

In [6]:
type(test_array[3])

numpy.float32

In [7]:
test_array.dtype

dtype('float32')

In [8]:
test_array.shape # tuple형태로 출력

(4,)

In [9]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape # tuple형태로 출력(3행4열)

(3, 4)

In [10]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape # (4,3,4 : 깊이, 행, 열)

(4, 3, 4)

In [11]:
np.array(tensor, int).ndim # ndim : 크기

3

In [12]:
np.array(tensor, int).size # data의 갯수

48

In [14]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float32).nbytes 
# 24 : 32bits = 4bytes -> 6 * 4bytes

24

In [15]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.int8).nbytes
# 6 : 8bits = 1bytes -> 6 * 1bytes

6

In [16]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float64).nbytes
# 48 : 64bits = 8bytes -> 6 * 8bytes

48

In [17]:
# reshape : array의 shape의 크기를 변경
# array의 size만 같다면 다차원으로 자유로이 변형가능
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [18]:
np.array(test_matrix).reshape(8, )

array([1, 2, 3, 4, 1, 2, 5, 8])

In [19]:
np.array(test_matrix).reshape(8, ).shape

(8,)

In [20]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [21]:
np.array(test_matrix).reshape(-1,2).shape # -1 : size를 기반으로 row개수를 지정

(4, 2)

In [22]:
# flatten : 다차원 array를 1차원 array로 변환
test_matrix = [[[1,2,3,4],[1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [23]:
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)
print(a[0,0])
print(a[0][0]) # a[0,0]과 동일

[[1 2 3]
 [4 5 6]]
1
1


In [24]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
a[:,2:] # 전체 row의 2열 이상
a[1,1:3] # 1행의 1열~2열
a[1:3] # 1행~2행 전체

array([[ 6,  7,  8,  9, 10]])