In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [3]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [4]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [5]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [9]:
sequences = []
for line in text.split('\n'): 
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 11


In [11]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [13]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [17]:
sequences = pad_sequences(sequences, maxlen=max_len)
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [18]:
sequences = np.array(sequences)
X = sequences[:,:-1] # 리스트의 마지막 값을 제외하고 저장한 것은 X
y = sequences[:,-1] # 리스트의 마지막 값만 저장한 것은 y. 이는 레이블에 해당됨.

In [19]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [20]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [21]:
y = to_categorical(y, vocab_size)

In [22]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [27]:
model = Sequential()
# Embedding(단어 갯수, 임베딩 후 벡터크기, 입력 시퀀스 길이)
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(SimpleRNN(32)) # SimpleRNN(은닉상태 크기)
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 0s - loss: 2.4768 - accuracy: 0.1818
Epoch 2/200
1/1 - 0s - loss: 2.4656 - accuracy: 0.2727
Epoch 3/200
1/1 - 0s - loss: 2.4541 - accuracy: 0.4545
Epoch 4/200
1/1 - 0s - loss: 2.4422 - accuracy: 0.4545
Epoch 5/200
1/1 - 0s - loss: 2.4299 - accuracy: 0.4545
Epoch 6/200
1/1 - 0s - loss: 2.4170 - accuracy: 0.4545
Epoch 7/200
1/1 - 0s - loss: 2.4037 - accuracy: 0.4545
Epoch 8/200
1/1 - 0s - loss: 2.3898 - accuracy: 0.4545
Epoch 9/200
1/1 - 0s - loss: 2.3752 - accuracy: 0.4545
Epoch 10/200
1/1 - 0s - loss: 2.3599 - accuracy: 0.4545
Epoch 11/200
1/1 - 0s - loss: 2.3440 - accuracy: 0.4545
Epoch 12/200
1/1 - 0s - loss: 2.3273 - accuracy: 0.4545
Epoch 13/200
1/1 - 0s - loss: 2.3099 - accuracy: 0.4545
Epoch 14/200
1/1 - 0s - loss: 2.2917 - accuracy: 0.4545
Epoch 15/200
1/1 - 0s - loss: 2.2728 - accuracy: 0.4545
Epoch 16/200
1/1 - 0s - loss: 2.2532 - accuracy: 0.3636
Epoch 17/200
1/1 - 0s - loss: 2.2329 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.2120 - accuracy: 0.3636
E

Epoch 147/200
1/1 - 0s - loss: 0.3388 - accuracy: 0.9091
Epoch 148/200
1/1 - 0s - loss: 0.3320 - accuracy: 0.9091
Epoch 149/200
1/1 - 0s - loss: 0.3253 - accuracy: 0.9091
Epoch 150/200
1/1 - 0s - loss: 0.3187 - accuracy: 1.0000
Epoch 151/200
1/1 - 0s - loss: 0.3123 - accuracy: 1.0000
Epoch 152/200
1/1 - 0s - loss: 0.3060 - accuracy: 1.0000
Epoch 153/200
1/1 - 0s - loss: 0.2997 - accuracy: 1.0000
Epoch 154/200
1/1 - 0s - loss: 0.2936 - accuracy: 1.0000
Epoch 155/200
1/1 - 0s - loss: 0.2877 - accuracy: 1.0000
Epoch 156/200
1/1 - 0s - loss: 0.2818 - accuracy: 1.0000
Epoch 157/200
1/1 - 0s - loss: 0.2761 - accuracy: 1.0000
Epoch 158/200
1/1 - 0s - loss: 0.2704 - accuracy: 1.0000
Epoch 159/200
1/1 - 0s - loss: 0.2649 - accuracy: 1.0000
Epoch 160/200
1/1 - 0s - loss: 0.2595 - accuracy: 1.0000
Epoch 161/200
1/1 - 0s - loss: 0.2542 - accuracy: 1.0000
Epoch 162/200
1/1 - 0s - loss: 0.2490 - accuracy: 1.0000
Epoch 163/200
1/1 - 0s - loss: 0.2439 - accuracy: 1.0000
Epoch 164/200
1/1 - 0s - loss: 

# predict 와 predict_class 차이점
- predict : 확률을 나타냄
- predict_class : label을 나타냄

In [28]:
def sentence_generation(model, t, current_word, n): 
    init_word = current_word 
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] 
        encoded = pad_sequences([encoded], maxlen=5) # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)

        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [29]:
print(sentence_generation(model, t, '경마장에', 4))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
경마장에 있는 말이 뛰고 있다


In [30]:
print(sentence_generation(model, t, '그의', 2))

그의 말이 법이다


In [31]:
print(sentence_generation(model, t, '가는', 5))

가는 말이 고와야 오는 말이 곱다
